- name: Install and enable tuned
  hosts: ubuntusrvs
  become: true

  tasks:
    - name: Install tuned package
      package:
        name: tuned
        state: present

    - name: Enable and start tuned service
      systemd:
        name: tuned
        enabled: yes
        state: started
